# Generated by Django 3.2.9 on 2021-11-27 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentNum', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='学号')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('sex', models.BooleanField(default=True, verbose_name='性别')),
                ('mobile', models.CharField(max_length=15, unique=True, verbose_name='手机')),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('modifyTime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='studentUnion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('unionName', models.CharField(max_length=20, verbose_name='社团名称')),
                ('unionNum', models.IntegerField(default=0, verbose_name='人数')),
                ('unionRoot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='robot.student')),
            ],
            options={
                'db_table': 'student_union',
            },
        ),
    ]
