# Generated by Django 3.2.9 on 2021-11-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0004_users_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='mode',
            field=models.CharField(blank=True, default='1', max_length=2, null=True, verbose_name='模式'),
        ),
    ]
