# Generated by Django 3.2.9 on 2021-11-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0005_alter_users_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='online',
            field=models.CharField(choices=[('0', '0'), ('1', '1')], default='0', max_length=2, verbose_name='在线'),
        ),
    ]
