# Generated by Django 3.2.9 on 2021-11-29 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0007_auto_20211128_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='address',
        ),
        migrations.RemoveField(
            model_name='users',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='users',
            name='nick_name',
        ),
        migrations.AddField(
            model_name='users',
            name='calorie',
            field=models.IntegerField(default=0, verbose_name='卡路里'),
        ),
    ]
