# Generated by Django 3.2.9 on 2021-11-29 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0009_auto_20211129_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='calorie',
            field=models.FloatField(default=0, verbose_name='卡路里'),
        ),
        migrations.AlterField(
            model_name='users',
            name='carbohydrate',
            field=models.FloatField(default=0, verbose_name='碳水化合物'),
        ),
        migrations.AlterField(
            model_name='users',
            name='fat',
            field=models.FloatField(default=0, verbose_name='脂肪'),
        ),
        migrations.AlterField(
            model_name='users',
            name='protein',
            field=models.FloatField(default=0, verbose_name='蛋白质'),
        ),
    ]
