# Generated by Django 3.2.9 on 2021-11-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0011_usersinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='age',
            field=models.IntegerField(default=0, verbose_name='年龄'),
        ),
        migrations.AddField(
            model_name='users',
            name='freqency',
            field=models.CharField(default='medium', max_length=10, verbose_name='频率'),
        ),
        migrations.AddField(
            model_name='users',
            name='height',
            field=models.FloatField(default=0, verbose_name='身高'),
        ),
        migrations.AddField(
            model_name='users',
            name='target',
            field=models.CharField(default='keep', max_length=6, verbose_name='目标'),
        ),
        migrations.AddField(
            model_name='users',
            name='weight',
            field=models.FloatField(default=0, verbose_name='体重'),
        ),
    ]
